[2025-01-10 16:14:29,434: INFO: main: Welcome to our custom logging for project 1]
[2025-01-10 16:15:55,916: INFO: main: Welcome to our custom logging for project 1]
[2025-01-10 16:15:57,887: INFO: main: Welcome to our custom logging for project 1]
[2025-01-13 15:43:03,619: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-13 15:43:03,626: INFO: common: yaml file: config\config.yaml loaded successfully.]
[2025-01-13 15:43:03,629: INFO: common: yaml file: params.yaml loaded successfully.]
[2025-01-13 15:43:03,631: INFO: common: yaml file: schema.yaml loaded successfully.]
[2025-01-13 15:43:05,360: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: BC01:1F4F13:5BE47C:78E7C7:6784E70A
Accept-Ranges: bytes
Date: Mon, 13 Jan 2025 10:12:28 GMT
Via: 1.1 varnish
X-Served-By: cache-bom4749-BOM
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1736763148.811108,VS0,VE375
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 5a583135d6e8dc12a3deaeca26f76e905012ed9b
Expires: Mon, 13 Jan 2025 10:17:28 GMT
Source-Age: 0

]
[2025-01-13 15:43:05,379: INFO: main: >>>>>>> stage Data Ingestion Stage completed <<<<<<<<

x==========x]
[2025-01-13 16:26:07,732: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-13 16:26:07,745: INFO: common: yaml file: config\config.yaml loaded successfully.]
[2025-01-13 16:26:07,750: INFO: common: yaml file: params.yaml loaded successfully.]
[2025-01-13 16:26:07,758: INFO: common: yaml file: schema.yaml loaded successfully.]
[2025-01-13 16:26:07,763: INFO: data_ingestion: File already exists of size: 23329]
[2025-01-13 16:26:07,771: INFO: main: >>>>>>> stage Data Ingestion Stage completed <<<<<<<<

x==========x]
[2025-01-13 16:26:07,778: INFO: main: >>>>>>> stage Data Validation Stage started <<<<<<<<]
[2025-01-13 16:26:07,784: INFO: common: yaml file: config\config.yaml loaded successfully.]
[2025-01-13 16:26:07,787: INFO: common: yaml file: params.yaml loaded successfully.]
[2025-01-13 16:26:07,805: INFO: common: yaml file: schema.yaml loaded successfully.]
[2025-01-13 16:26:07,815: ERROR: main: 'NoneType' object has no attribute 'unzip_data_dir']
Traceback (most recent call last):
  File "E:\udemy\project_1\main.py", line 24, in <module>
    obj.initiate_data_validation()
  File "E:\udemy\project_1\src\project_1\pipeline\data_validation_pipeline.py", line 15, in initiate_data_validation
    data_validation.validate_dataset_columns()
  File "E:\udemy\project_1\src\project_1\components\data_validation.py", line 33, in validate_dataset_columns
    raise e
  File "E:\udemy\project_1\src\project_1\components\data_validation.py", line 15, in validate_dataset_columns
    data=pd.read_csv(self.config.unzip_data_dir)
AttributeError: 'NoneType' object has no attribute 'unzip_data_dir'
[2025-01-13 16:29:00,139: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-13 16:29:00,142: INFO: common: yaml file: config\config.yaml loaded successfully.]
[2025-01-13 16:29:00,146: INFO: common: yaml file: params.yaml loaded successfully.]
[2025-01-13 16:29:00,150: INFO: common: yaml file: schema.yaml loaded successfully.]
[2025-01-13 16:29:00,152: INFO: data_ingestion: File already exists of size: 23329]
[2025-01-13 16:29:00,156: INFO: main: >>>>>>> stage Data Ingestion Stage completed <<<<<<<<

x==========x]
[2025-01-13 16:29:00,157: INFO: main: >>>>>>> stage Data Validation Stage started <<<<<<<<]
[2025-01-13 16:29:00,165: INFO: common: yaml file: config\config.yaml loaded successfully.]
[2025-01-13 16:29:00,168: INFO: common: yaml file: params.yaml loaded successfully.]
[2025-01-13 16:29:00,172: INFO: common: yaml file: schema.yaml loaded successfully.]
[2025-01-13 16:29:00,181: ERROR: main: 'NoneType' object has no attribute 'unzip_data_dir']
Traceback (most recent call last):
  File "E:\udemy\project_1\main.py", line 24, in <module>
    obj.initiate_data_validation()
  File "E:\udemy\project_1\src\project_1\pipeline\data_validation_pipeline.py", line 15, in initiate_data_validation
    data_validation.validate_dataset_columns()
  File "E:\udemy\project_1\src\project_1\components\data_validation.py", line 33, in validate_dataset_columns
    raise e
  File "E:\udemy\project_1\src\project_1\components\data_validation.py", line 15, in validate_dataset_columns
    data=pd.read_csv(self.config.unzip_data_dir)
AttributeError: 'NoneType' object has no attribute 'unzip_data_dir'
[2025-01-13 16:34:00,675: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-13 16:34:00,678: INFO: common: yaml file: config\config.yaml loaded successfully.]
[2025-01-13 16:34:00,679: INFO: common: yaml file: params.yaml loaded successfully.]
[2025-01-13 16:34:00,683: INFO: common: yaml file: schema.yaml loaded successfully.]
[2025-01-13 16:34:00,684: INFO: data_ingestion: File already exists of size: 23329]
[2025-01-13 16:34:00,691: INFO: main: >>>>>>> stage Data Ingestion Stage completed <<<<<<<<

x==========x]
[2025-01-13 16:34:00,693: INFO: main: >>>>>>> stage Data Validation Stage started <<<<<<<<]
[2025-01-13 16:34:00,699: INFO: common: yaml file: config\config.yaml loaded successfully.]
[2025-01-13 16:34:00,713: INFO: common: yaml file: params.yaml loaded successfully.]
[2025-01-13 16:34:00,766: INFO: common: yaml file: schema.yaml loaded successfully.]
[2025-01-13 16:34:00,799: ERROR: main: 'NoneType' object has no attribute 'unzip_data_dir']
Traceback (most recent call last):
  File "E:\udemy\project_1\main.py", line 24, in <module>
    data_validation.initiate_data_validation()
  File "E:\udemy\project_1\src\project_1\pipeline\data_validation_pipeline.py", line 15, in initiate_data_validation
    data_validation.validate_dataset_columns()
  File "E:\udemy\project_1\src\project_1\components\data_validation.py", line 33, in validate_dataset_columns
    raise e
  File "E:\udemy\project_1\src\project_1\components\data_validation.py", line 15, in validate_dataset_columns
    data = pd.read_csv(self.config.unzip_data_dir)
AttributeError: 'NoneType' object has no attribute 'unzip_data_dir'
[2025-01-13 16:40:06,635: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-13 16:40:06,638: INFO: common: yaml file: config\config.yaml loaded successfully.]
[2025-01-13 16:40:06,639: INFO: common: yaml file: params.yaml loaded successfully.]
[2025-01-13 16:40:06,645: INFO: common: yaml file: schema.yaml loaded successfully.]
[2025-01-13 16:40:06,647: INFO: data_ingestion: File already exists of size: 23329]
[2025-01-13 16:40:06,654: INFO: main: >>>>>>> stage Data Ingestion Stage completed <<<<<<<<

x==========x]
[2025-01-13 16:40:06,655: INFO: main: >>>>>>> stage Data Validation Stage started <<<<<<<<]
[2025-01-13 16:40:06,660: INFO: common: yaml file: config\config.yaml loaded successfully.]
[2025-01-13 16:40:06,667: INFO: common: yaml file: params.yaml loaded successfully.]
[2025-01-13 16:40:06,671: INFO: common: yaml file: schema.yaml loaded successfully.]
[2025-01-13 16:40:06,672: ERROR: main: 'DataValidation' object has no attribute 'validate_dataset_columns']
Traceback (most recent call last):
  File "E:\udemy\project_1\main.py", line 24, in <module>
    data_validation.initiate_data_validation()
  File "E:\udemy\project_1\src\project_1\pipeline\data_validation_pipeline.py", line 15, in initiate_data_validation
    data_validation.validate_dataset_columns()
AttributeError: 'DataValidation' object has no attribute 'validate_dataset_columns'
[2025-01-13 16:40:39,694: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-13 16:40:39,697: INFO: common: yaml file: config\config.yaml loaded successfully.]
[2025-01-13 16:40:39,699: INFO: common: yaml file: params.yaml loaded successfully.]
[2025-01-13 16:40:39,706: INFO: common: yaml file: schema.yaml loaded successfully.]
[2025-01-13 16:40:39,711: INFO: data_ingestion: File already exists of size: 23329]
[2025-01-13 16:40:39,717: INFO: main: >>>>>>> stage Data Ingestion Stage completed <<<<<<<<

x==========x]
[2025-01-13 16:40:39,718: INFO: main: >>>>>>> stage Data Validation Stage started <<<<<<<<]
[2025-01-13 16:40:39,723: INFO: common: yaml file: config\config.yaml loaded successfully.]
[2025-01-13 16:40:39,725: INFO: common: yaml file: params.yaml loaded successfully.]
[2025-01-13 16:40:39,731: INFO: common: yaml file: schema.yaml loaded successfully.]
[2025-01-13 16:40:39,732: ERROR: main: 'NoneType' object has no attribute 'unzip_data_dir']
Traceback (most recent call last):
  File "E:\udemy\project_1\main.py", line 24, in <module>
    data_validation.initiate_data_validation()
  File "E:\udemy\project_1\src\project_1\pipeline\data_validation_pipeline.py", line 15, in initiate_data_validation
    data_validation.validate_all_columns()
  File "E:\udemy\project_1\src\project_1\components\data_validation.py", line 34, in validate_all_columns
    raise e
  File "E:\udemy\project_1\src\project_1\components\data_validation.py", line 15, in validate_all_columns
    data = pd.read_csv(self.config.unzip_data_dir)
AttributeError: 'NoneType' object has no attribute 'unzip_data_dir'
[2025-01-13 16:41:35,282: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-13 16:41:35,286: INFO: common: yaml file: config\config.yaml loaded successfully.]
[2025-01-13 16:41:35,289: INFO: common: yaml file: params.yaml loaded successfully.]
[2025-01-13 16:41:35,294: INFO: common: yaml file: schema.yaml loaded successfully.]
[2025-01-13 16:41:35,296: INFO: data_ingestion: File already exists of size: 23329]
[2025-01-13 16:41:35,302: INFO: main: >>>>>>> stage Data Ingestion Stage completed <<<<<<<<

x==========x]
[2025-01-13 16:41:35,303: INFO: main: >>>>>>> stage Data Validation Stage started <<<<<<<<]
[2025-01-13 16:41:35,319: INFO: common: yaml file: config\config.yaml loaded successfully.]
[2025-01-13 16:41:35,322: INFO: common: yaml file: params.yaml loaded successfully.]
[2025-01-13 16:41:35,330: INFO: common: yaml file: schema.yaml loaded successfully.]
[2025-01-13 16:41:35,331: ERROR: main: 'NoneType' object has no attribute 'unzip_data_dir']
Traceback (most recent call last):
  File "E:\udemy\project_1\main.py", line 24, in <module>
    data_validation.initiate_data_validation()
  File "E:\udemy\project_1\src\project_1\pipeline\data_validation_pipeline.py", line 15, in initiate_data_validation
    data_validation.validate_all_columns()
  File "E:\udemy\project_1\src\project_1\components\data_validation.py", line 34, in validate_all_columns
    raise e
  File "E:\udemy\project_1\src\project_1\components\data_validation.py", line 15, in validate_all_columns
    data = pd.read_csv(self.config.unzip_data_dir)
AttributeError: 'NoneType' object has no attribute 'unzip_data_dir'
[2025-01-13 16:44:10,296: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-13 16:44:10,299: INFO: common: yaml file: config\config.yaml loaded successfully.]
[2025-01-13 16:44:10,300: INFO: common: yaml file: params.yaml loaded successfully.]
[2025-01-13 16:44:10,310: INFO: common: yaml file: schema.yaml loaded successfully.]
[2025-01-13 16:44:10,314: INFO: data_ingestion: File already exists of size: 23329]
[2025-01-13 16:44:10,320: INFO: main: >>>>>>> stage Data Ingestion Stage completed <<<<<<<<

x==========x]
[2025-01-13 16:44:10,322: INFO: main: >>>>>>> stage Data Validation Stage started <<<<<<<<]
[2025-01-13 16:44:10,326: INFO: common: yaml file: config\config.yaml loaded successfully.]
[2025-01-13 16:44:10,328: INFO: common: yaml file: params.yaml loaded successfully.]
[2025-01-13 16:44:10,334: INFO: common: yaml file: schema.yaml loaded successfully.]
[2025-01-13 16:44:10,335: ERROR: main: local variable 'config' referenced before assignment]
Traceback (most recent call last):
  File "E:\udemy\project_1\main.py", line 24, in <module>
    data_validation.initiate_data_validation()
  File "E:\udemy\project_1\src\project_1\pipeline\data_validation_pipeline.py", line 13, in initiate_data_validation
    data_validation_config = config.get_data_validation_config()
  File "E:\udemy\project_1\src\project_1\config\configuration.py", line 29, in get_data_validation_config
    config=config.data_validation
UnboundLocalError: local variable 'config' referenced before assignment
[2025-01-13 16:45:32,336: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-13 16:45:32,339: INFO: common: yaml file: config\config.yaml loaded successfully.]
[2025-01-13 16:45:32,340: INFO: common: yaml file: params.yaml loaded successfully.]
[2025-01-13 16:45:32,349: INFO: common: yaml file: schema.yaml loaded successfully.]
[2025-01-13 16:45:32,352: INFO: data_ingestion: File already exists of size: 23329]
[2025-01-13 16:45:32,359: INFO: main: >>>>>>> stage Data Ingestion Stage completed <<<<<<<<

x==========x]
[2025-01-13 16:45:32,361: INFO: main: >>>>>>> stage Data Validation Stage started <<<<<<<<]
[2025-01-13 16:45:32,366: INFO: common: yaml file: config\config.yaml loaded successfully.]
[2025-01-13 16:45:32,367: INFO: common: yaml file: params.yaml loaded successfully.]
[2025-01-13 16:45:32,372: INFO: common: yaml file: schema.yaml loaded successfully.]
[2025-01-13 16:45:32,407: INFO: main: >>>>>>> stage Data Validation Stage completed <<<<<<<<

x==========x]
[2025-01-13 17:17:47,379: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-13 17:17:47,384: INFO: common: yaml file: config\config.yaml loaded successfully.]
[2025-01-13 17:17:47,386: INFO: common: yaml file: params.yaml loaded successfully.]
[2025-01-13 17:17:47,398: INFO: common: yaml file: schema.yaml loaded successfully.]
[2025-01-13 17:17:47,401: INFO: data_ingestion: File already exists of size: 23329]
[2025-01-13 17:17:47,405: INFO: main: >>>>>>> stage Data Ingestion Stage completed <<<<<<<<

x==========x]
[2025-01-13 17:17:47,406: INFO: main: >>>>>>> stage Data Validation Stage started <<<<<<<<]
[2025-01-13 17:17:47,414: INFO: common: yaml file: config\config.yaml loaded successfully.]
[2025-01-13 17:17:47,420: INFO: common: yaml file: params.yaml loaded successfully.]
[2025-01-13 17:17:47,425: INFO: common: yaml file: schema.yaml loaded successfully.]
[2025-01-13 17:17:47,457: INFO: main: >>>>>>> stage Data Validation Stage completed <<<<<<<<

x==========x]
[2025-01-13 17:17:47,458: INFO: main: >>>>>>> stage Data Transformation Stage started <<<<<<<<]
[2025-01-13 17:17:47,464: INFO: common: yaml file: config\config.yaml loaded successfully.]
[2025-01-13 17:17:47,466: INFO: common: yaml file: params.yaml loaded successfully.]
[2025-01-13 17:17:47,471: INFO: common: yaml file: schema.yaml loaded successfully.]
[2025-01-13 17:17:47,524: INFO: data_transformation: Splited data into train and test]
[2025-01-13 17:17:47,525: INFO: data_transformation: (1199, 12)]
[2025-01-13 17:17:47,526: INFO: data_transformation: (400, 12)]
[2025-01-13 17:17:47,529: INFO: main: >>>>>>> stage Data Transformation Stage completed <<<<<<<<

x==========x]
[2025-01-13 17:18:16,991: INFO: main: >>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2025-01-13 17:18:16,996: INFO: common: yaml file: config\config.yaml loaded successfully.]
[2025-01-13 17:18:16,998: INFO: common: yaml file: params.yaml loaded successfully.]
[2025-01-13 17:18:17,013: INFO: common: yaml file: schema.yaml loaded successfully.]
[2025-01-13 17:18:17,018: INFO: data_ingestion: File already exists of size: 23329]
[2025-01-13 17:18:17,023: INFO: main: >>>>>>> stage Data Ingestion Stage completed <<<<<<<<

x==========x]
[2025-01-13 17:18:17,027: INFO: main: >>>>>>> stage Data Validation Stage started <<<<<<<<]
[2025-01-13 17:18:17,036: INFO: common: yaml file: config\config.yaml loaded successfully.]
[2025-01-13 17:18:17,038: INFO: common: yaml file: params.yaml loaded successfully.]
[2025-01-13 17:18:17,045: INFO: common: yaml file: schema.yaml loaded successfully.]
[2025-01-13 17:18:17,086: INFO: main: >>>>>>> stage Data Validation Stage completed <<<<<<<<

x==========x]
[2025-01-13 17:18:17,087: INFO: main: >>>>>>> stage Data Transformation Stage started <<<<<<<<]
[2025-01-13 17:18:17,097: INFO: common: yaml file: config\config.yaml loaded successfully.]
[2025-01-13 17:18:17,100: INFO: common: yaml file: params.yaml loaded successfully.]
[2025-01-13 17:18:17,107: INFO: common: yaml file: schema.yaml loaded successfully.]
[2025-01-13 17:18:17,157: INFO: data_transformation: Splited data into train and test]
[2025-01-13 17:18:17,164: INFO: data_transformation: (1199, 12)]
[2025-01-13 17:18:17,167: INFO: data_transformation: (400, 12)]
[2025-01-13 17:18:17,173: INFO: main: >>>>>>> stage Data Transformation Stage completed <<<<<<<<

x==========x]
